name: Python Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Git Checkout
        uses: actions/checkout@v4

      # Configure SSH access
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Connect to EC2 and deploy application
      - name: Deploy Python App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Go to application folder
            cd /home/ec2-user/python-app

            # Pull latest code
            git pull origin main

            # Create virtual environment if not exists
            python3 -m venv venv

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Stop old application if running
            pkill -f app.py || true

            # Start application in background
            nohup python3 app.py > output.log 2>&1 &

          EOF
