name: Python Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Go to correct folder
            cd /home/ec2-user/docker_python_flask-project

            # Pull latest code
            git pull origin main

            # Create venv if not exists
            python3 -m venv venv

            # Activate venv
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Stop old app
            pkill -f app.py || true

            # Start app
            nohup python3 app.py > output.log 2>&1 &

          EOF
